### ISSUE TITLE
README.md Usage

### ISSUE THREAD

**Issue by nguyenhung15913** [menghif/static-dodo#2]
The usage should be more clear with user input.
Assume you have a file named " Silver Blaze.txt". The following command will result into "file or directory not found"
```
dodo-ssg -i Silver Blaze.txt
```

**Comment by humphd** [comment]
I was just coming to file the same issue.  I would like to see better explanation of what each of the example Usage lines does.  Think "teaching a user how to use this" vs. "writing a reference."
